#### Import numpy, scipy, numpy.linalg, scipy.linalg

In [1]:
import numpy as np
import numpy.linalg as linalg
import scipy
import scipy.linalg

#### Calculate hibert matrix and compare it with the library generated matrix

In [3]:
m_size = 7

In [4]:
hilbert_matrix = np.reshape([(1/(i+j+1)) for i in range(m_size) for j in range(m_size)],(m_size,m_size))

In [5]:
print(hilbert_matrix)

[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125     ]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1       ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1
  0.09090909]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
  0.08333333]
 [0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
  0.07692308]]


In [6]:
hilbert_matrix_linalg = scipy.linalg.hilbert(7)

In [7]:
print(hilbert_matrix_linalg - hilbert_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### Calculate e

In [8]:
e = np.reshape([1 if i== j else 0 for i in range(m_size) for j in range(m_size)],(m_size,m_size))

In [9]:
print(e)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


In [14]:
for i in range(m_size):
    print(e[i])

[1 0 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 0 1 0 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 0 1]


#### Calculate inverse matrix and compared with library generated matrix

In [27]:
h_inverse = np.array([linalg.solve(hilbert_matrix, e[i]) for i in range(m_size)])

print(h_inverse.shape)
print(h_inverse)

(7, 7)
[[ 4.90000000e+01 -1.17600000e+03  8.82000001e+03 -2.94000000e+04
   4.85100000e+04 -3.88080000e+04  1.20120000e+04]
 [-1.17600000e+03  3.76320000e+04 -3.17520000e+05  1.12896000e+06
  -1.94040000e+06  1.59667200e+06 -5.04504000e+05]
 [ 8.82000001e+03 -3.17520000e+05  2.85768000e+06 -1.05840000e+07
   1.87110000e+07 -1.57172400e+07  5.04504000e+06]
 [-2.94000000e+04  1.12896000e+06 -1.05840000e+07  4.03200000e+07
  -7.27650001e+07  6.20928000e+07 -2.01801600e+07]
 [ 4.85100000e+04 -1.94040000e+06  1.87110000e+07 -7.27650001e+07
   1.33402500e+08 -1.15259760e+08  3.78378000e+07]
 [-3.88080000e+04  1.59667200e+06 -1.57172400e+07  6.20928000e+07
  -1.15259760e+08  1.00590336e+08 -3.32972640e+07]
 [ 1.20120000e+04 -5.04504000e+05  5.04504000e+06 -2.01801600e+07
   3.78378000e+07 -3.32972640e+07  1.10990880e+07]]


In [22]:
print(np.linalg.inv(hilbert_matrix))

[[ 4.90000000e+01 -1.17600000e+03  8.82000001e+03 -2.94000000e+04
   4.85100000e+04 -3.88080000e+04  1.20120000e+04]
 [-1.17600000e+03  3.76320000e+04 -3.17520000e+05  1.12896000e+06
  -1.94040000e+06  1.59667200e+06 -5.04504000e+05]
 [ 8.82000001e+03 -3.17520000e+05  2.85768000e+06 -1.05840000e+07
   1.87110000e+07 -1.57172400e+07  5.04504000e+06]
 [-2.94000000e+04  1.12896000e+06 -1.05840000e+07  4.03200000e+07
  -7.27650001e+07  6.20928000e+07 -2.01801600e+07]
 [ 4.85100000e+04 -1.94040000e+06  1.87110000e+07 -7.27650001e+07
   1.33402500e+08 -1.15259760e+08  3.78378000e+07]
 [-3.88080000e+04  1.59667200e+06 -1.57172400e+07  6.20928000e+07
  -1.15259760e+08  1.00590336e+08 -3.32972640e+07]
 [ 1.20120000e+04 -5.04504000e+05  5.04504000e+06 -2.01801600e+07
   3.78378000e+07 -3.32972640e+07  1.10990880e+07]]


In [26]:
print(scipy.linalg.invhilbert(m_size))

[[ 4.90000000e+01 -1.17600000e+03  8.82000000e+03 -2.94000000e+04
   4.85100000e+04 -3.88080000e+04  1.20120000e+04]
 [-1.17600000e+03  3.76320000e+04 -3.17520000e+05  1.12896000e+06
  -1.94040000e+06  1.59667200e+06 -5.04504000e+05]
 [ 8.82000000e+03 -3.17520000e+05  2.85768000e+06 -1.05840000e+07
   1.87110000e+07 -1.57172400e+07  5.04504000e+06]
 [-2.94000000e+04  1.12896000e+06 -1.05840000e+07  4.03200000e+07
  -7.27650000e+07  6.20928000e+07 -2.01801600e+07]
 [ 4.85100000e+04 -1.94040000e+06  1.87110000e+07 -7.27650000e+07
   1.33402500e+08 -1.15259760e+08  3.78378000e+07]
 [-3.88080000e+04  1.59667200e+06 -1.57172400e+07  6.20928000e+07
  -1.15259760e+08  1.00590336e+08 -3.32972640e+07]
 [ 1.20120000e+04 -5.04504000e+05  5.04504000e+06 -2.01801600e+07
   3.78378000e+07 -3.32972640e+07  1.10990880e+07]]


#### Calculate the multiplication of Hibert Matrix and it's Inverse

In [30]:
x = h_inverse@hilbert_matrix
print(x)

[[ 1.00000000e+00 -2.27373675e-13 -2.25671334e-13  2.03104200e-13
  -2.59075589e-13  8.53928039e-13 -2.02316796e-13]
 [ 1.23161798e-11  1.00000000e+00  6.34549204e-12 -8.62132588e-12
   1.92319897e-11 -1.70687538e-11  6.80074800e-12]
 [ 9.88428383e-12 -1.16415322e-10  1.00000000e+00  9.78547910e-11
   2.14660614e-12  1.90090092e-10 -9.03950419e-11]
 [ 1.60031988e-10  0.00000000e+00  2.27949610e-10  9.99999999e-01
  -1.56751380e-10 -2.94699080e-10  2.00389722e-10]
 [ 2.32124351e-10 -9.31322575e-10  5.94462306e-10  1.60702585e-09
   1.00000000e+00  1.84283059e-09 -5.33498372e-11]
 [-1.33250021e-09 -9.31322575e-10 -1.45031019e-09 -1.02302726e-09
   2.12313117e-10  9.99999998e-01 -5.72023454e-10]
 [ 6.98491931e-10  2.32830644e-10  4.65661287e-10  0.00000000e+00
   6.98491931e-10  1.04773790e-09  1.00000000e+00]]


In [32]:
error_matrix = np.identity(7)-x
print(error_matrix)

[[ 1.92734717e-13  2.27373675e-13  2.25671334e-13 -2.03104200e-13
   2.59075589e-13 -8.53928039e-13  2.02316796e-13]
 [-1.23161798e-11 -2.18278728e-11 -6.34549204e-12  8.62132588e-12
  -1.92319897e-11  1.70687538e-11 -6.80074800e-12]
 [-9.88428383e-12  1.16415322e-10 -1.75843340e-10 -9.78547910e-11
  -2.14660614e-12 -1.90090092e-10  9.03950419e-11]
 [-1.60031988e-10  0.00000000e+00 -2.27949610e-10  6.24249763e-10
   1.56751380e-10  2.94699080e-10 -2.00389722e-10]
 [-2.32124351e-10  9.31322575e-10 -5.94462306e-10 -1.60702585e-09
  -3.91803479e-10 -1.84283059e-09  5.33498372e-11]
 [ 1.33250021e-09  9.31322575e-10  1.45031019e-09  1.02302726e-09
  -2.12313117e-10  2.01905526e-09  5.72023454e-10]
 [-6.98491931e-10 -2.32830644e-10 -4.65661287e-10  0.00000000e+00
  -6.98491931e-10 -1.04773790e-09 -2.32830644e-10]]


#### Calculate the inverse of the inversed Hibert Matrix

In [34]:
error_matrix2 = np.linalg.inv(h_inverse)-hilbert_matrix
print(error_matrix2)

[[ 1.10315090e-10 -1.16449073e-11 -2.91565661e-11 -3.42968987e-11
  -3.60154406e-11 -3.65965869e-11 -3.63666597e-11]
 [ 9.72528724e-11 -4.91839902e-12 -1.96174466e-11 -2.41841269e-11
  -2.60625410e-11 -2.67953160e-11 -2.69111816e-11]
 [ 8.67648731e-11 -1.14430687e-12 -1.38624945e-11 -1.79856130e-11
  -1.98191463e-11 -2.06516609e-11 -2.09368634e-11]
 [ 7.82089393e-11  1.04916076e-12 -1.01632591e-11 -1.39113165e-11
  -1.56641922e-11 -1.65311931e-11 -1.69041586e-11]
 [ 7.11291304e-11  2.36380360e-12 -7.66275932e-12 -1.10925436e-11
  -1.27546307e-11 -1.36222700e-11 -1.40400191e-11]
 [ 6.51910192e-11  3.16455195e-12 -5.90344440e-12 -9.06147379e-12
  -1.06328557e-11 -1.14840498e-11 -1.19226018e-11]
 [ 6.01480532e-11  3.65199537e-12 -4.62493932e-12 -7.54916962e-12
  -9.03417618e-12 -9.86058457e-12 -1.03060754e-11]]
